# Generated by Django 4.2.14 on 2024-08-29 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_brand_remove_item_category_delete_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bike',
            fields=[
                ('bike_id', models.AutoField(primary_key=True, serialize=False)),
                ('bike_title', models.CharField(max_length=255)),
                ('bike_model', models.CharField(max_length=255)),
                ('overview', models.TextField()),
                ('p_p_day', models.CharField(max_length=5, verbose_name='Price per day')),
                ('abs', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=30)),
                ('ftype', models.CharField(choices=[('', 'Select'), ('Petrol', 'Petrol'), ('CNG', 'CNG'), ('EV', 'EV')], default='Select', max_length=30)),
                ('b_break', models.CharField(choices=[('Drum brakes', 'Drum brakes'), ('Disc brake', 'Disc brake'), ('Hydraulic disc brakes', 'Hydraulic disc brakes')], default='Drum brakes', max_length=30, verbose_name='Break Type')),
                ('reg', models.CharField(max_length=15)),
                ('b_img', models.ImageField(upload_to='bikes/')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.brand', verbose_name='Name of Brand')),
            ],
        ),
    ]
